=== Andrewyuan34/clang_libraries_companion/documents/json_schema/compilation_database_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/mdadams/clang_libraries_companion",
  "title": "Compilation Database",
  "description": "A format for specifying how to replay single compilations independently of the build system.",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "directory",
      "file"
    ],
    "anyOf": [
      {"required": ["arguments"]},
      {"required": ["command"]}
    ],
    "properties": {
      "directory": {
        "description": "The working directory of the compilation.  All paths specified in the command or file fields must be either absolute or relative to this directory.",
        "type": "string"
      },
      "file": {
        "description": "The main translation unit source processed by this compilation step.  This is used by tools as the key into the compilation database.  There can be multiple command objects for the same file, for example if the same source file is compiled with different configurations.",
        "type": "string"
      },
      "arguments": {
        "description": "The compile command argv as list of strings.  This should run the compilation step for the translation unit file.  arguments[0] should be the executable name, such as clang++.  Arguments should not be escaped, but ready to pass to execvp().",
        "type": "array",
        "minItems": 1
      },
      "command": {
        "description": "The compile command as a single shell-escaped string.  Arguments may be shell quoted and escaped following platform conventions, with ‘\"’ and ‘\\’ being the only special characters. Shell expansion is not supported.",
        "type": "string"
      },
      "output": {
        "description": "The name of the output created by this compilation step. This field is optional. It can be used to distinguish different processing modes of the same input file.",
        "type": "string"
      }
    }
  }
}

=== Andrewyuan34/clang_libraries_companion/slides/examples/compilation_database/compile_commands.json
[
{
  "directory": "/home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/compilation_database",
  "command": "/home/frodo/public/ugls_lab-10.4.2/bin/c++ -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -isystem /home/frodo/public/ugls_lab-10.4.2/packages/clang/include -isystem /usr/include/libxml2 -std=gnu++20 -fno-rtti -o CMakeFiles/arg_adjuster.dir/adjuster.cpp.o -c /home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/compilation_database/adjuster.cpp",
  "file": "/home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/compilation_database/adjuster.cpp",
  "output": "CMakeFiles/arg_adjuster.dir/adjuster.cpp.o"
},
{
  "directory": "/home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/compilation_database",
  "command": "/home/frodo/public/ugls_lab-10.4.2/bin/c++ -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -isystem /home/frodo/public/ugls_lab-10.4.2/packages/clang/include -isystem /usr/include/libxml2 -std=gnu++20 -fno-rtti -o CMakeFiles/arg_adjuster.dir/utility.cpp.o -c /home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/compilation_database/utility.cpp",
  "file": "/home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/compilation_database/utility.cpp",
  "output": "CMakeFiles/arg_adjuster.dir/utility.cpp.o"
},
{
  "directory": "/home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/compilation_database",
  "command": "/home/frodo/public/ugls_lab-10.4.2/bin/c++ -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -isystem /home/frodo/public/ugls_lab-10.4.2/packages/clang/include -isystem /usr/include/libxml2 -std=gnu++20 -fno-rtti -o CMakeFiles/fixed_database.dir/fixed.cpp.o -c /home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/compilation_database/fixed.cpp",
  "file": "/home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/compilation_database/fixed.cpp",
  "output": "CMakeFiles/fixed_database.dir/fixed.cpp.o"
},
{
  "directory": "/home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/compilation_database",
  "command": "/home/frodo/public/ugls_lab-10.4.2/bin/c++ -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -isystem /home/frodo/public/ugls_lab-10.4.2/packages/clang/include -isystem /usr/include/libxml2 -std=gnu++20 -fno-rtti -o CMakeFiles/fixed_database.dir/utility.cpp.o -c /home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/compilation_database/utility.cpp",
  "file": "/home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/compilation_database/utility.cpp",
  "output": "CMakeFiles/fixed_database.dir/utility.cpp.o"
},
{
  "directory": "/home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/compilation_database",
  "command": "/home/frodo/public/ugls_lab-10.4.2/bin/c++ -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -isystem /home/frodo/public/ugls_lab-10.4.2/packages/clang/include -isystem /usr/include/libxml2 -std=gnu++20 -fno-rtti -o CMakeFiles/json_database.dir/json.cpp.o -c /home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/compilation_database/json.cpp",
  "file": "/home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/compilation_database/json.cpp",
  "output": "CMakeFiles/json_database.dir/json.cpp.o"
},
{
  "directory": "/home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/compilation_database",
  "command": "/home/frodo/public/ugls_lab-10.4.2/bin/c++ -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -isystem /home/frodo/public/ugls_lab-10.4.2/packages/clang/include -isystem /usr/include/libxml2 -std=gnu++20 -fno-rtti -o CMakeFiles/json_database.dir/utility.cpp.o -c /home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/compilation_database/utility.cpp",
  "file": "/home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/compilation_database/utility.cpp",
  "output": "CMakeFiles/json_database.dir/utility.cpp.o"
}
]

=== Andrewyuan34/clang_libraries_companion/slides/examples/ast_visitor_1/compile_commands.json
[
{
  "directory": "/home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/ast_visitor_1",
  "command": "/home/frodo/public/ugls_lab-10.4.2/bin/c++ -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -isystem /home/frodo/public/ugls_lab-10.4.2/packages/clang/include -isystem /usr/include/libxml2 -std=gnu++20 -fno-rtti -o CMakeFiles/app.dir/main.cpp.o -c /home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/ast_visitor_1/main.cpp",
  "file": "/home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/ast_visitor_1/main.cpp",
  "output": "CMakeFiles/app.dir/main.cpp.o"
},
{
  "directory": "/home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/ast_visitor_1",
  "command": "/home/frodo/public/ugls_lab-10.4.2/bin/c++   -std=gnu++20 -o CMakeFiles/dummy.dir/data/simple_1.cpp.o -c /home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/ast_visitor_1/data/simple_1.cpp",
  "file": "/home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/ast_visitor_1/data/simple_1.cpp",
  "output": "CMakeFiles/dummy.dir/data/simple_1.cpp.o"
},
{
  "directory": "/home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/ast_visitor_1",
  "command": "/home/frodo/public/ugls_lab-10.4.2/bin/c++   -std=gnu++20 -o CMakeFiles/dummy.dir/data/hello.cpp.o -c /home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/ast_visitor_1/data/hello.cpp",
  "file": "/home/yiboy/Desktop/clang_exercise/clang_libraries_companion/slides/examples/ast_visitor_1/data/hello.cpp",
  "output": "CMakeFiles/dummy.dir/data/hello.cpp.o"
}
]
